name: CD for Dev on PR approved

on:
  pull_request_target:
    types:
      - closed

jobs:

  Merge_and_Deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: PR_INFO
        run:  |
          echo PR #${{ github.event.number }} has been merged
          echo Commit #${{ github.sha }} 
          echo PR-REF: ${{ github.event.pull_request.head.sha }}
          echo REF: ${{ github.ref }}

      - name: Wait for CI
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          # ref: ${{ github.event.pull_request.head.sha }}
          running-workflow-name: CI
          check-name: build
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 200

      - name: Execute
        run: /bin/bash pipelines/deploy.sh dev

