name: CD for Test on tag

on:
  push:
    tags:
      - t**

jobs:
  Deploy_Test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Execute
        run: /bin/bash pipelines/deploy.sh test

